### ISSUE TITLE
Return the first image of a post if no featured image is set

### ISSUE THREAD

**Issue by luisherranz** [frontity/wp-org-connection#8]

**Comment by luisherranz** [comment]
If `content_media` is present, we should return the first image `conent_media[0]`. If it's not, we should take a look inside `content` and retrieve a valid media object with the info we can collect from the HTML.

**Comment by luisherranz** [comment]
@SantosGuillamot could you please let me know if this problem is affecting now a demo or an integration to tag it accordingly?

**Comment by SantosGuillamot** [comment]
Yes, it was for a demo. This is the link of the blog:

https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A5

And this is the link for the demo:

https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A4

**Comment by luisherranz** [comment]
Perfect, thanks @SantosGuillamot!

**Comment by luisherranz** [comment]
We can create a serverless microservice for the demos which adds `content_media` to the response.

**Comment by DAreRodz** [comment]
Ok, as the first part of this issue is affecting integrations too I'm going to fix that in  https://github.com/frontity/saturn-theme, just for the post list view.

**Comment by luisherranz** [comment]
We'll solve the other part here: https://github.com/frontity/frontity/issues/130
